#!/bin/bash

# network=canms

# docker network create $network --driver bridge

# docker run --rm --name zookeeper-server --network $network \
#   -e ALLOW_ANONYMOUS_LOGIN=yes \
#   bitnami/zookeeper:latest

# docker run --rm --name kafka-server --network $network \
#   -e ALLOW_PLAINTEXT_LISTENER=yes \
#   -e KAFKA_CFG_ZOOKEEPER_CONNECT=localhost:2181 \
#   bitnami/kafka:latest

# TODO don't use guest user
docker run --rm --name rabbitmq --hostname rabbitmq-broker -d -p 5672:5672 rabbitmq:3
